export default {
  namespace: 'global',
  reducers: {
    TOGGLE_COLLAPSED: 'TOGGLE_COLLAPSED',
    INCREMENT_COUNTER: 'INCREMENT_COUNTER',
    DECREMENT_COUNTER: 'DECREMENT_COUNTER',
    FETCHUSER_SUCCESS: 'FETCHUSER_SUCCESS',
    FETCHUSER_ERROR: 'FETCHUSER_ERROR',
    TIMEOUT_ERROR: 'TIMEOUT_ERROR',
    POSTS_RECEIVED: 'POSTS_RECEIVED',
  },
  effects: {
    INCREMENT_COUNTER_ASYNC: 'INCREMENT_COUNTER_ASYNC',
    FETCHUSER_REQUESTED_ASYNC: 'FETCHUSER_REQUESTED_ASYNC',
    POSTS_RECEIVED_ASYNC: 'POSTS_RECEIVED_ASYNC',
  },
};
