export const TOGGLE_COLLAPSED = 'TOGGLE_COLLAPSED';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const INCREMENT_COUNTER_ASYNC = 'INCREMENT_COUNTER_ASYNC';
export const FETCHUSER_SUCCESS = 'FETCHUSER_SUCCESS';
export const FETCHUSER_ERROR = 'FETCHUSER_ERROR';
export const FETCHUSER_REQUESTED = 'FETCHUSER_REQUESTED';
